// Code generated by goyacc parser.y. DO NOT EDIT.

//line parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser.y:2

import (
	"github.com/dcaiafa/go-expr/expr/internal/ast"
	"github.com/dcaiafa/go-expr/expr/types"
)

//line parser.y:11
type yySymType struct {
	yys  int
	num  float64
	str  string
	ast  ast.AST
	expr ast.Expr
}

const LEXERR = 57346
const ID = 57347
const kIN = 57348
const NUMBER = 57349
const STRING = 57350
const OR = 57351
const AND = 57352
const LE = 57353
const GE = 57354
const EQ = 57355

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEXERR",
	"ID",
	"kIN",
	"NUMBER",
	"STRING",
	"OR",
	"AND",
	"'<'",
	"LE",
	"'>'",
	"GE",
	"EQ",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"';'",
	"'!'",
	"'('",
	"')'",
	"','",
	"'['",
	"']'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 39,
	11, 0,
	12, 0,
	13, 0,
	14, 0,
	15, 0,
	-2, 8,
	-1, 40,
	11, 0,
	12, 0,
	13, 0,
	14, 0,
	15, 0,
	-2, 9,
	-1, 41,
	11, 0,
	12, 0,
	13, 0,
	14, 0,
	15, 0,
	-2, 10,
	-1, 42,
	11, 0,
	12, 0,
	13, 0,
	14, 0,
	15, 0,
	-2, 11,
	-1, 43,
	11, 0,
	12, 0,
	13, 0,
	14, 0,
	15, 0,
	-2, 12,
	-1, 48,
	6, 0,
	-2, 17,
}

const yyPrivate = 57344

const yyLast = 100

var yyAct = [...]int{

	3, 4, 20, 21, 22, 23, 24, 25, 26, 27,
	28, 54, 56, 53, 32, 55, 52, 35, 36, 31,
	37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
	47, 48, 51, 10, 17, 15, 9, 27, 28, 10,
	33, 15, 9, 1, 34, 14, 12, 7, 8, 6,
	13, 14, 11, 16, 30, 57, 13, 58, 29, 16,
	5, 19, 18, 20, 21, 22, 23, 24, 25, 26,
	27, 28, 29, 50, 49, 2, 18, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 25, 26, 27,
	28, 20, 21, 22, 23, 24, 25, 26, 27, 28,
}
var yyPact = [...]int{

	28, -1000, 14, -1000, 52, -1000, 34, -3, -1000, -1000,
	-1000, -1000, -1000, 28, 33, -1000, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	-3, 28, -7, -1000, -13, -1000, -1000, 80, 66, 71,
	71, 71, 71, 71, 19, 19, -1000, -1000, -9, -8,
	-12, -1000, -1000, -1000, 28, -1000, 28, -1000, -1000,
}
var yyPgo = [...]int{

	0, 75, 74, 73, 0, 1, 60, 47, 52, 48,
	46, 44, 43,
}
var yyR1 = [...]int{

	0, 12, 1, 1, 4, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 6, 6,
	7, 7, 7, 7, 7, 7, 9, 9, 8, 2,
	2, 3, 3, 10, 11, 11,
}
var yyR2 = [...]int{

	0, 1, 3, 1, 1, 1, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 1,
	1, 1, 1, 1, 1, 3, 2, 1, 4, 1,
	0, 3, 1, 3, 3, 1,
}
var yyChk = [...]int{

	-1000, -12, -1, -4, -5, -6, 21, -7, -9, 8,
	5, -8, -10, 22, 17, 7, 25, 20, 10, 9,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 6,
	-7, 22, -4, 7, -11, -4, -4, -5, -5, -5,
	-5, -5, -5, -5, -5, -5, -5, -5, -5, -2,
	-3, -4, 23, 26, 24, 23, 24, -4, -4,
}
var yyDef = [...]int{

	0, -2, 1, 3, 4, 5, 0, 19, 20, 21,
	22, 23, 24, 0, 0, 27, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	18, 30, 0, 26, 0, 35, 2, 6, 7, -2,
	-2, -2, -2, -2, 13, 14, 15, 16, -2, 0,
	29, 32, 25, 33, 0, 28, 0, 34, 31,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 21, 3, 3, 3, 3, 3, 3,
	22, 23, 18, 16, 24, 17, 3, 19, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 20,
	11, 3, 13, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 25, 3, 26,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 12,
	14, 15,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:39
		{
			yylex.(*lex).Program = yyDollar[1].ast.(*ast.Program)
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:41
		{
			yyDollar[1].ast.(*ast.Program).AddExpr(yyDollar[3].expr.(ast.Expr))
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:42
		{
			yyVAL.ast = ast.NewProgram(yyDollar[1].expr.(ast.Expr))
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:47
		{
			yyVAL.expr = ast.NewAndExpr(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:48
		{
			yyVAL.expr = ast.NewOrExpr(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:49
		{
			yyVAL.expr = ast.NewBinaryExpr(yyDollar[1].expr, ast.Lt, yyDollar[3].expr)
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:50
		{
			yyVAL.expr = ast.NewBinaryExpr(yyDollar[1].expr, ast.Le, yyDollar[3].expr)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:51
		{
			yyVAL.expr = ast.NewBinaryExpr(yyDollar[1].expr, ast.Gt, yyDollar[3].expr)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:52
		{
			yyVAL.expr = ast.NewBinaryExpr(yyDollar[1].expr, ast.Ge, yyDollar[3].expr)
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:53
		{
			yyVAL.expr = ast.NewBinaryExpr(yyDollar[1].expr, ast.Eq, yyDollar[3].expr)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:54
		{
			yyVAL.expr = ast.NewBinaryExpr(yyDollar[1].expr, ast.Plus, yyDollar[3].expr)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:55
		{
			yyVAL.expr = ast.NewBinaryExpr(yyDollar[1].expr, ast.Minus, yyDollar[3].expr)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:56
		{
			yyVAL.expr = ast.NewBinaryExpr(yyDollar[1].expr, ast.Times, yyDollar[3].expr)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:57
		{
			yyVAL.expr = ast.NewBinaryExpr(yyDollar[1].expr, ast.Div, yyDollar[3].expr)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:58
		{
			yyVAL.expr = ast.NewInExpr(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:60
		{
			yyVAL.expr = ast.NewNegateExpr(yyDollar[2].expr)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:64
		{
			yyVAL.expr = ast.NewLiteralExpr(types.String, yyDollar[1].str)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:65
		{
			yyVAL.expr = ast.NewSimpleRefExpr(yyDollar[1].str)
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:68
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:70
		{
			yyVAL.expr = ast.NewLiteralExpr(types.Number, -yyDollar[2].num)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:71
		{
			yyVAL.expr = ast.NewLiteralExpr(types.Number, yyDollar[1].num)
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:73
		{
			yyVAL.expr = ast.NewCallExpr(yyDollar[1].expr, yyDollar[3].ast.(*ast.Params))
		}
	case 30:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:76
		{
			yyVAL.ast = &ast.Params{}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:78
		{
			yyDollar[1].ast.(*ast.Params).AddParam(yyDollar[3].expr.(ast.Expr))
			yyVAL.ast = yyDollar[1].ast
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:79
		{
			yyVAL.ast = ast.NewParams(yyDollar[1].expr)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:81
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:83
		{
			yyDollar[1].expr.(*ast.ArrayLiteralExpr).AddElement(yyDollar[3].expr.(ast.Expr))
			yyVAL.expr = yyDollar[1].expr
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:84
		{
			yyVAL.expr = ast.NewArrayLiteralExpr(yyDollar[1].expr)
		}
	}
	goto yystack /* stack new state and value */
}
